### ISSUE TITLE
Why are we keeping duplicate versions?

### ISSUE THREAD

**Issue by focusaurus** [reactioncommerce/docker-base#3]
Neither @rosshadden or I are clear on why it's necessary to keep duplicate copies of versioned files in here. Could we add to the README why that is being done?

**Comment by aldeed** [comment]
@focusaurus Can you clarify what you mean? Essentially each Docker tag has its own folder so that we know exactly what was used to publish that tag, and all tags are rebuilt and republished every time we merge to `trunk`.

**Comment by focusaurus** [comment]
We discussed over zoom so I'll close this.
